# Project: Taller Hash
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Hash.o Validacion.o
LINKOBJ  = main.o Hash.o Validacion.o
LIBS     = -L"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/lib" -L"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/include" -I"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/include" -I"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"A:/SOFTWARE/Dev-C++/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = "Taller Hash.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = A:\SOFTWARE\Dev-C++\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Hash.o: Hash.cpp
	$(CPP) -c Hash.cpp -o Hash.o $(CXXFLAGS)

Validacion.o: Validacion.cpp
	$(CPP) -c Validacion.cpp -o Validacion.o $(CXXFLAGS)
